# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'



target 'FooFii' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 
use_frameworks! # this allows you to use import Firebase
pod 'Firebase', '>= 4.0.0'
pod 'Firebase/Core'
pod 'FirebaseAuth', '>= 4.5.0'
pod 'GeoFire', '>= 2.0.0'
pod 'SwiftLocation', '>= 3.2.1'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'

  # Pods for FooFii

end
